= ISO/TC 211 Multi-Lingual Glossary of Terms (MLGT) online version

image:https://img.shields.io/github/workflow/status/geolexica/isotc211.geolexica.org/deploy?label=production%20deployment&style=flat-square[Deployment Status]

== Introduction

NOTE: This repository is only meant for internal consumption!

The online version of the ISO/TC 211 Multi Lingual Glossary of Terms is served
by the Geolexica platform, an open-source platform for machine-readable
open terminologies.

This repository contains the source of the https://isotc211.geolexica.org site.

The site is managed by the ISO/TC 211 TMG together with Ribose.

== Sites

`main`:: https://isotc211.geolexica.org/
`staging`:: https://isotc211-staging.geolexica.org

== How to add/remove entries or suggest changes?

For change suggestions, contact ISO/TC 211 TMG.

This terminology database is managed by the ISO/TC 211 TMG, and it only considers
requests from within ISO/TC 211. The database is not directly community-managed or community-sourced.


== ISO/TC 211 MLGT component overview

Components involved in ISO/TC 211 MLGT solution:

. isotc211.geolexica.org: **this repository**.
  Renders the MLGT into HTML, JSON-LD and other Web-friendly formats.

. MLGT data set for Geolexica:
  see https://github.com/geolexica/isotc211-glossary[geolexica/isotc211-glossary].
  Hosts all concept data in YAML;
  bundles facilities for converting authoritative spreadsheet data into YAML.
  Candidate to become authoritative source, contingent upon factual usage of Glossarist by TMG.

. (2.0 workflow, now) Glossarist desktop application:
  https://github.com/geolexica/geolexica-desktop[Geolexica Desktop].
  is used to manage the MLGT database.

. (1.0 workflow) Manually managed spreadsheets:
  see https://github.com/ISO-TC211/mlgt-data[ISO-TC211/mlgt-data].
  Currently the authoritative source in 1.0 workflow.


=== Change lifecycle (2.0, current)

. Requested changes are directed to ISO/TC 211 TMG.

. Adding, updating, approving concepts & terms in ISO/TC 211 MLGT Geolexica database
  is done by TMG using Glossarist desktop.

. As changes are made, new versions of the MLGT Geolexica database are created,
  and isotc211.geolexica.org is deployed with the latest dataset version.


=== Change lifecycle (1.0, deprecated)

. Requested changes are directed to ISO/TC 211 TMG.

. When a change is approved, TMG publishes a new version of ISO/TC 211 "`Multi-Lingual Glossary of Terms`".

. TMG uploads the new MLGT version to mlgt-data repository.

. From the updated mlgt-data, a new snapshot of the database is created in isotc211-glossary repository.

. After a new snapshot of the database is committed to isotc211-glossary,
  isotc211.geolexica.org is deployed with the latest database version.


== Internal operations

NOTE: These steps are only intended for the internal operator of the site!


=== Building the site

. Ensure isotc211-glossary submodule is up-to-date.

. Run `npm install`

. Run `make _site`


=== Deployment

Please push all changes to the `staging` branch, and changes will be automatically deployed and reflected on the staging site.

If your changes are to be made public to the production site, please contact Ribose.


=== Rendering of HTML

Jekyll is used to render YAML into HTML.

NOTE: Since Jekyll Collections have this flaw where YAML files can't be directly
rendered, a hack is implemented in the Makefile `_concepts` target,
so that every YAML file is converted into AsciiDoc by padding `---` at the end.
