---
layout: base-page
title: About
permalink: /about/
bodyClass: page
nav_items: [concepts, posts, stats, feedback, registers, semantic-search]
---
:page-liquid:

The ISO/TC 211 Multi-Lingual Glossary of Terms (MLGT)
is the glossary for geographic information technology from
https://www.iso.org/committee/54904.html[ISO/TC 211 Geographic information/Geomatics].

The online version of the MLGT served on the Geolexica platform
fully reflect entries from the authoritative English terms
that originate from ISO/TC 211 standards.

Specifically:

* English terms and definitions are from published
  ISO/TC 211 standards (normative);

* Terminology entries are translated across fourteen languages.
  While these are considered informative, they may be based on
  authoritative national standards in their respective countries.


== Current content ({{ site.data.metadata.version }} edition)

The current contents in the online version of the ISO/TC 211 MLGT are
from the 5th release of the MLGT ({{ site.data.metadata.version }} edition),
consisting of:

* {{ site.data.metadata.concept_count }} English language terminology entries (terms/definitions)
from published ISO/TC 211 standards as of June 2020;

* {{ site.data.metadata.term_count }} translated terminology entries (full or partial)
covering fourteen languages, which represents close to all of
the participating countries in ISO/TC 211.


== Resource links

The MLGT spreadsheet and corresponding documentation can be downloaded
from the
https://committee.iso.org/sites/tc211/home/re.html[ISO/TC 211 Resources page].


== Responsibility

The MLGT is managed by the ISO/TC 211 Terminology Maintenance Group (TMG).
The convenor of the TMG is Mr. Reese Plews of Japan.

The online version of ISO/TC 211 MLGT is jointly managed by the TMG and
https://www.ribose.com[Ribose],
the official ISO/TC 211 web service provider and
Registration Authority of the
https://geodetic.isotc211.org[ISO Geodetic Register].


== Feedback

Feedback for ISO/TC 211 MLGT can be submitted on the
link:/feedback[Feedback] page.

Identified issues that are publicly visible are maintained at the
https://github.com/ISO-TC211/TMG/issues[TMG GitHub Issues] page.


== Copyright

(C) {{ site.time | date: "%Y" }} International Organization for Standardization.

All rights reserved. Unless otherwise specified, no part of this
site or its documents may be reproduced or utilized otherwise in any form or by any
means, electronic or mechanical, including photocopying, or posting on the
internet or an intranet, without prior written permission. Permission can
be requested from the address below.

[%hardbreaks]
International Organization for Standardization
Chemin de Blandonnet 8
CP 401
1214 Vernier, Geneva
Switzerland
mailto:copyright@iso.org[copyright@iso.org]
https://www.iso.org/[www.iso.org]
